language: python
python:
  - "3.7"

install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential python3-dev python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

before_script: 
  - pip install -r requirements.txt

script: 
  -  python manage.py test dinosaurios
notifications:
email: false